create table todo_foundation_finance_requirement(requirement_id bigint not null auto_increment,gate_code varchar(8) not null,requirement_code varchar(64) not null,requirement_name varchar(200) not null,check_kind varchar(32) not null,source_status varchar(24) not null,decision_ref varchar(32) null,source_ref varchar(500) not null,sort_order int not null,remark varchar(1000) null,create_time datetime not null default current_timestamp,primary key(requirement_id),unique key uk_todo_foundation_finance(gate_code,requirement_code),constraint chk_todo_foundation_finance_kind check(check_kind in('FEE_PLAN_CORE','PAYMENT_SERVICE','NODE_FEE_SCHEMA','SUPPORT_TABLES','RISK_SCHEMA','SOURCE_ONLY')),constraint chk_todo_foundation_finance_source check(source_status in('CONFIRMED','NEEDS_DECISION','NEEDS_REVIEW')))engine=InnoDB default charset=utf8mb4 comment='v0.2 Foundation财务准入要求';
-- Checklist only. No business fact, formula, collection owner or decision is created here.
insert into todo_foundation_finance_requirement(gate_code,requirement_code,requirement_name,check_kind,source_status,decision_ref,source_ref,sort_order,remark)values
('G-06','FEE_PLAN_CORE_PRECISION','收费计划与金额精度','FEE_PLAN_CORE','CONFIRMED',null,'sql/customer_contract_module_20260603.sql:200-217',10,'应收与实收必须为decimal(14,2)，并保留确认与开票状态'),
('G-06','PAYMENT_CONFIRMATION_SERVICE','回款确认事实入口','PAYMENT_SERVICE','CONFIRMED',null,'ruoyi-system/src/main/java/com/ruoyi/system/service/contract/ContractPaymentService.java',20,'强类型命令、权限、状态日志和事务事件入口已存在'),
('G-06','PAYMENT_IDEMPOTENT_EVENT','回款事件幂等键','PAYMENT_SERVICE','CONFIRMED',null,'ruoyi-system/src/main/java/com/ruoyi/system/service/contract/ContractPaymentService.java:117-119',30,'PAYMENT_CONFIRMED幂等键包含合同、计划和日志标识'),
('G-06','NODE_FEE_SCHEMA','节点型收费字段','NODE_FEE_SCHEMA','CONFIRMED','Q-009','doc/v0.2-prd-readiness-gap-analysis.md:199',40,'要求trigger_type/node/business/owner/due_rule/risk_calc六字段'),
('G-06','RECEIVABLE_COLLECTION_REFUND_TABLES','应收催收退款事实表','SUPPORT_TABLES','CONFIRMED','Q-009','doc/v0.2-prd-readiness-gap-analysis.md:200',50,'要求应收触发、催收记录和退款表'),
('G-06','RISK_FEE_SCHEMA','风险代理计算结构','RISK_SCHEMA','CONFIRMED','Q-012','doc/v0.2-prd-readiness-gap-analysis.md:179,200',60,'要求风险计算表及合同风险标记/基数/比例'),
('G-06','Q009_NODE_COLLECTION_POLICY','节点清单、金额与催收Owner','SOURCE_ONLY','NEEDS_DECISION','Q-009','ruoyi-admin/src/main/resources/db/migration/V0_20_10__v02_prd_definition_catalog.sql:50',70,'不得由研发推定'),
('G-06','Q012_RISK_FORMULA_POLICY','风险公式、舍入与审核边界','SOURCE_ONLY','NEEDS_DECISION','Q-012','ruoyi-admin/src/main/resources/db/migration/V0_20_10__v02_prd_definition_catalog.sql:59',80,'不得由研发推定'),
('G-06','FINANCE_BUSINESS_SIGNOFF','财务与业务签字','SOURCE_ONLY','NEEDS_REVIEW',null,'doc/v0.2-prd-readiness-gap-analysis.md:328',90,'需确认公式版本、税费、退款、重算和验收责任');
