-- Close the lead-flow navigation and source-label read model.
--
-- V0.20.52 established the audit table as an explicit schema boundary. This
-- migration contains only temporary-table DDL plus permanent DML enclosed by
-- one transaction. A failure before COMMIT leaves a legal V0.20.52 database:
-- the audit table exists and remains empty, while source/menu data is unchanged.
drop temporary table if exists tmp_lead_source_governance;
create temporary table tmp_lead_source_governance (
  lead_id bigint not null,
  original_source_code varchar(40) null,
  governed_source_code varchar(40) not null,
  governance_result varchar(16) not null,
  primary key (lead_id)
) engine=innodb;

insert into tmp_lead_source_governance(
  lead_id,original_source_code,governed_source_code,governance_result)
select l.lead_id,
  l.source_code,
  case
    when active_source.setting_id is not null then active_source.setting_code
    else concat('LEGACY_',upper(substr(sha2(concat(
      cast(l.lead_id as char),':',
      coalesce(nullif(trim(l.source_code),''),'EMPTY')),256),1,24)))
  end,
  case when active_source.setting_id is not null then 'RETAINED' else 'REMAPPED' end
from biz_lead l
left join biz_lead_setting active_source
  on active_source.setting_type='source'
 and active_source.setting_code=trim(l.source_code)
 and active_source.status='0'
where l.del_flag='0';

-- Fail before permanent DML if staging did not cover every live lead.
drop temporary table if exists tmp_lead_source_governance_guard;
create temporary table tmp_lead_source_governance_guard (
  violation_count bigint not null,
  constraint chk_tmp_lead_source_governance_guard check (violation_count=0)
) engine=innodb;
insert into tmp_lead_source_governance_guard(violation_count)
select abs(
  (select count(*) from biz_lead where del_flag='0')
  -(select count(*) from tmp_lead_source_governance)
);
delete from tmp_lead_source_governance_guard;

start transaction;

insert into biz_lead_source_governance_audit(
  migration_code,lead_id,original_source_code,governed_source_code,
  governance_result,create_by,create_time)
select 'V0_20_53',lead_id,original_source_code,governed_source_code,
  governance_result,'migration',sysdate()
from tmp_lead_source_governance;

insert into biz_lead_setting(
  setting_type,setting_code,setting_name,color,order_num,status,
  create_by,create_time,remark)
select distinct 'source',stage.governed_source_code,
  concat('Legacy source: ',
    coalesce(nullif(trim(stage.original_source_code),''),'EMPTY')),
  '#64748B',999,'0','migration',sysdate(),
  concat('Generated by V0_20_53 for historical source value: ',
    coalesce(nullif(trim(stage.original_source_code),''),'EMPTY'))
from tmp_lead_source_governance stage
where stage.governance_result='REMAPPED'
  and not exists(
    select 1 from biz_lead_setting existing
    where existing.setting_type='source'
      and existing.setting_code=stage.governed_source_code
  );

update biz_lead l
join tmp_lead_source_governance stage on stage.lead_id=l.lead_id
set l.source_code=stage.governed_source_code,
    l.update_by='migration',
    l.update_time=sysdate()
where not (l.source_code <=> stage.governed_source_code);

insert into biz_business_tag(
  tag_code,tag_name,applicable_business_type,tag_level,color,status,
  create_by,create_time)
select concat('LEAD_SOURCE_',upper(source.setting_code)),
  source.setting_name,'LEAD','SOURCE',source.color,'0','migration',sysdate()
from biz_lead_setting source
where source.setting_type='source'
  and source.status='0'
  and exists(
    select 1 from tmp_lead_source_governance stage
    where stage.governed_source_code=source.setting_code
  )
  and not exists(
    select 1 from biz_business_tag existing
    where existing.tag_code=concat('LEAD_SOURCE_',upper(source.setting_code))
  );

-- A live lead has exactly one source-level relation. Non-source business tags
-- and deleted leads are deliberately untouched.
delete relation
from biz_business_tag_rel relation
join biz_business_tag tag on tag.tag_id=relation.tag_id
join tmp_lead_source_governance stage
  on stage.lead_id=relation.business_id
where relation.business_type='LEAD'
  and tag.applicable_business_type='LEAD'
  and tag.tag_level='SOURCE'
  and tag.tag_code<>concat('LEAD_SOURCE_',upper(stage.governed_source_code));

insert into biz_business_tag_rel(
  business_type,business_id,tag_id,tag_source,confirm_status,
  confirmed_by,confirmed_at,create_by,create_time)
select 'LEAD',l.lead_id,tag.tag_id,'SYSTEM',l.tag_confirm_status,
  l.tag_confirm_by,l.tag_confirm_time,'migration',sysdate()
from biz_lead l
join tmp_lead_source_governance stage on stage.lead_id=l.lead_id
join biz_business_tag tag
  on tag.tag_code=concat('LEAD_SOURCE_',upper(stage.governed_source_code))
 and tag.applicable_business_type='LEAD'
 and tag.tag_level='SOURCE'
where not exists(
  select 1 from biz_business_tag_rel existing
  where existing.business_type='LEAD'
    and existing.business_id=l.lead_id
    and existing.tag_id=tag.tag_id
);

-- V0.20.48 created functional permissions. Add only addressable pages and
-- inherit existing list grants without broadening role authority.
set @lead_directory_id=(
  select menu_id from sys_menu where parent_id=0 and path='lead'
  order by menu_id limit 1
);

insert into sys_menu(
  menu_name,parent_id,order_num,path,component,`query`,route_name,is_frame,is_cache,
  menu_type,visible,status,perms,icon,create_by,create_time)
select route.menu_name,@lead_directory_id,route.order_num,route.path,route.component,
  null,route.route_name,1,0,'C','0','0',route.perms,route.icon,'migration',sysdate()
from (
  select '疑似无效复核' menu_name,8 order_num,'invalid-review' path,
    'lead/review/index' component,'LeadInvalidReview' route_name,
    'lead:invalid-review:list' perms,'audit' icon
  union all
  select '线索重试队列',9,'retry','lead/retry/index',
    'LeadRetryWorkbench','lead:retry:list','time'
  union all
  select 'Dead-Pool',10,'dead-pool','lead/dead-pool/index',
    'LeadDeadPool','lead:dead-pool:list','lock'
  union all
  select '轮转与重试策略',11,'assignment-policy','lead/policy/index',
    'LeadAssignmentPolicy','lead:assignment-policy:list','tree-table'
) route
where @lead_directory_id is not null
  and not exists(
    select 1 from sys_menu existing
    where existing.parent_id=@lead_directory_id
      and existing.path=route.path
  );

insert into sys_role_menu(role_id,menu_id)
select distinct granted.role_id,page.menu_id
from sys_role_menu granted
join sys_menu permission_menu on permission_menu.menu_id=granted.menu_id
join sys_menu page
  on page.parent_id=@lead_directory_id
 and page.component in (
   'lead/review/index','lead/retry/index',
   'lead/dead-pool/index','lead/policy/index')
 and page.perms=permission_menu.perms
where not exists(
  select 1 from sys_role_menu existing
  where existing.role_id=granted.role_id
    and existing.menu_id=page.menu_id
);

-- Postcondition gate: every live lead must use an active source catalogue value
-- and have exactly one matching SOURCE relation.
insert into tmp_lead_source_governance_guard(violation_count)
select count(*)
from biz_lead l
where l.del_flag='0'
  and (
    not exists(
      select 1 from biz_lead_setting source
      where source.setting_type='source'
        and source.status='0'
        and source.setting_code=l.source_code
    )
    or 1<>(
      select count(*)
      from biz_business_tag_rel relation
      join biz_business_tag tag on tag.tag_id=relation.tag_id
      where relation.business_type='LEAD'
        and relation.business_id=l.lead_id
        and tag.applicable_business_type='LEAD'
        and tag.tag_level='SOURCE'
    )
    or 1<>(
      select count(*)
      from biz_business_tag_rel relation
      join biz_business_tag tag on tag.tag_id=relation.tag_id
      where relation.business_type='LEAD'
        and relation.business_id=l.lead_id
        and tag.applicable_business_type='LEAD'
        and tag.tag_level='SOURCE'
        and tag.tag_code=concat('LEAD_SOURCE_',upper(l.source_code))
    )
  );

-- FAILURE_INJECTION_POINT_BEFORE_COMMIT
commit;

drop temporary table if exists tmp_lead_source_governance_guard;
drop temporary table if exists tmp_lead_source_governance;
