create table todo_schedule_plan (
  plan_id bigint not null auto_increment,
  previous_todo_id bigint not null,
  template_version_id bigint not null,
  business_type varchar(64) not null,
  business_id bigint not null,
  timezone varchar(64) not null default 'Asia/Shanghai',
  rule_version_id bigint null,
  first_contact_at datetime not null,
  current_window_code varchar(32) null,
  status varchar(20) not null default 'ACTIVE',
  completion_reason varchar(64) null,
  completed_at datetime null,
  create_time datetime not null,
  update_time datetime not null,
  version int not null default 0,
  primary key (plan_id),
  key idx_todo_schedule_plan_business (business_type,business_id,status),
  key idx_todo_schedule_plan_previous (previous_todo_id),
  constraint chk_todo_schedule_plan_status check (status in ('ACTIVE','CONTACTED','COMPLETED','CANCELLED','EXHAUSTED'))
) engine=innodb comment='Reusable persisted Todo schedule plan';

create table todo_schedule_window (
  window_id bigint not null auto_increment,
  plan_id bigint not null,
  window_code varchar(32) not null,
  window_order int not null,
  day_offset int not null,
  start_time time not null,
  end_time time not null,
  materialize_at datetime not null,
  due_at datetime not null,
  max_attempts int not null default 1,
  occurrence_no int not null default 1,
  status varchar(20) not null default 'PENDING',
  claimed_at datetime null,
  completed_at datetime null,
  error_code varchar(128) null,
  cancel_reason varchar(64) null,
  create_time datetime not null,
  update_time datetime not null,
  version int not null default 0,
  primary key (window_id),
  unique key uk_todo_schedule_window (plan_id,window_code),
  key idx_todo_schedule_window_due (status,due_at),
  key idx_todo_schedule_window_materialize (status,materialize_at),
  constraint chk_todo_schedule_window_status check (status in ('PENDING','PROCESSING','MATERIALIZED','CANCELLED')),
  constraint chk_todo_schedule_window_period check (due_at>materialize_at),
  constraint chk_todo_schedule_window_attempts check (max_attempts>0),
  constraint fk_todo_schedule_window_plan foreign key (plan_id) references todo_schedule_plan(plan_id)
) engine=innodb comment='Immutable absolute Todo schedule window';

create table todo_schedule_occurrence (
  occurrence_id bigint not null auto_increment,
  plan_id bigint not null,
  window_id bigint not null,
  window_code varchar(32) not null,
  occurrence_no int not null,
  occurrence_key varchar(192) not null,
  due_at datetime not null,
  todo_id bigint null,
  status varchar(20) not null default 'RETRY',
  result_code varchar(64) null,
  claimed_at datetime null,
  completed_at datetime null,
  error_code varchar(128) null,
  error_message varchar(1000) null,
  create_time datetime not null,
  update_time datetime not null,
  version int not null default 0,
  primary key (occurrence_id),
  unique key uk_todo_schedule_occurrence (plan_id,window_code,occurrence_no),
  unique key uk_todo_schedule_occurrence_key (occurrence_key),
  key idx_todo_schedule_occurrence_due (status,due_at),
  key idx_todo_schedule_occurrence_todo (todo_id),
  constraint chk_todo_schedule_occurrence_status check (status in ('RETRY','CLAIMED','MATERIALIZED','COMPLETED','CANCELLED')),
  constraint fk_todo_schedule_occurrence_plan foreign key (plan_id) references todo_schedule_plan(plan_id),
  constraint fk_todo_schedule_occurrence_window foreign key (window_id) references todo_schedule_window(window_id)
) engine=innodb comment='Idempotent materialization occurrence for a Todo schedule window';
