create table todo_configuration_resource_item (
  resource_item_id bigint not null auto_increment,
  resource_type varchar(24) not null,
  resource_code varchar(128) not null,
  resource_name varchar(128) not null,
  description varchar(500) null,
  business_type varchar(32) not null,
  value_json json not null,
  status varchar(16) not null default 'ACTIVE',
  sort_order int not null default 0,
  version int not null default 0,
  create_by varchar(64) null,
  create_time datetime not null default current_timestamp,
  update_by varchar(64) null,
  update_time datetime null,
  primary key (resource_item_id),
  unique key uk_todo_config_resource (resource_type,business_type,resource_code),
  key idx_todo_config_resource_lookup (resource_type,business_type,status,sort_order),
  constraint chk_todo_config_resource_type check (resource_type in ('FIELD','MATERIAL','DOD_RECIPE')),
  constraint chk_todo_config_resource_status check (status in ('ACTIVE','DISABLED'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

insert into todo_configuration_resource_item(resource_type,resource_code,resource_name,description,business_type,value_json,status,sort_order,create_by) values
('FIELD','contactResult','首联结果','首联或重试后的联系结果','LEAD',json_object('type','string'),'ACTIVE',10,'migration'),
('FIELD','contactedAt','联系时间','实际完成联系的时间','LEAD',json_object('type','string','format','date-time'),'ACTIVE',20,'migration'),
('FIELD','name','客户姓名','自然人客户姓名','LEAD',json_object('type','string'),'ACTIVE',30,'migration'),
('FIELD','city','所在城市','客户当前所在城市','LEAD',json_object('type','string'),'ACTIVE',40,'migration'),
('FIELD','demand','客户诉求','客户咨询或委托诉求','LEAD',json_object('type','string'),'ACTIVE',50,'migration'),
('FIELD','visited','是否到所','客户是否已经到所面谈','LEAD',json_object('type','boolean'),'ACTIVE',60,'migration'),
('FIELD','reviewResult','复核结果','主管复核结论','LEAD',json_object('type','string'),'ACTIVE',70,'migration'),
('FIELD','reviewOpinion','复核意见','主管复核说明','LEAD',json_object('type','string'),'ACTIVE',80,'migration'),
('FIELD','attemptStage','重试阶段','无法联系后的重试阶段','LEAD',json_object('type','string'),'ACTIVE',90,'migration'),
('FIELD','attemptCount','拨号次数','累计联系尝试次数','LEAD',json_object('type','integer'),'ACTIVE',100,'migration'),
('FIELD','progressType','进展类型','客户跟进的实质进展类型','CUSTOMER',json_object('type','string'),'ACTIVE',10,'migration'),
('FIELD','progressAt','进展时间','实质进展发生时间','CUSTOMER',json_object('type','string','format','date-time'),'ACTIVE',20,'migration'),
('FIELD','remark','进展说明','客户跟进说明','CUSTOMER',json_object('type','string'),'ACTIVE',30,'migration'),
('FIELD','disposition','处置结果','长期无进展客户的处置结论','CUSTOMER',json_object('type','string'),'ACTIVE',40,'migration'),
('FIELD','conflictResult','冲突审查结果','合同签署前的冲突审查结论','CONTRACT',json_object('type','string'),'ACTIVE',10,'migration'),
('FIELD','contractNo','合同编号','正式委托合同编号','CONTRACT',json_object('type','string'),'ACTIVE',20,'migration'),
('FIELD','signedAt','签署时间','合同完成签署时间','CONTRACT',json_object('type','string','format','date-time'),'ACTIVE',30,'migration'),
('FIELD','paymentAmount','收款金额','本次确认的收款金额','CONTRACT',json_object('type','number'),'ACTIVE',40,'migration'),
('FIELD','paymentAt','收款时间','财务确认到账时间','CONTRACT',json_object('type','string','format','date-time'),'ACTIVE',50,'migration'),
('FIELD','invoiceNo','发票号码','已开具发票号码','CONTRACT',json_object('type','string'),'ACTIVE',60,'migration'),
('FIELD','signResult','签署结果','合同签署处理结果','CONTRACT',json_object('type','string'),'ACTIVE',70,'migration'),
('FIELD','classification','案件分类','案管确认的案件分类','CASE',json_object('type','string'),'ACTIVE',10,'migration'),
('FIELD','assignmentResult','分案结果','案件分配处理结果','CASE',json_object('type','string'),'ACTIVE',20,'migration'),
('FIELD','acceptResult','接案结果','承办律师接案确认结果','CASE',json_object('type','string'),'ACTIVE',30,'migration'),
('FIELD','transferReason','转案原因','申请转案的业务原因','CASE',json_object('type','string'),'ACTIVE',40,'migration'),
('FIELD','transferResult','转案审批结果','转案申请的审批结论','CASE',json_object('type','string'),'ACTIVE',50,'migration'),
('FIELD','progressResult','办理进展','事项阶段办理进展','MATTER',json_object('type','string'),'ACTIVE',10,'migration'),
('FIELD','nodeResult','节点结果','关键业务节点处理结果','MATTER',json_object('type','string'),'ACTIVE',20,'migration'),
('FIELD','hearingDate','开庭日期','案件实际开庭日期','MATTER',json_object('type','string','format','date'),'ACTIVE',30,'migration'),
('FIELD','hearingSummary','庭审摘要','开庭情况与庭审结论摘要','MATTER',json_object('type','string'),'ACTIVE',40,'migration'),
('FIELD','followupResult','文书跟进结果','裁判文书周期跟进结果','MATTER',json_object('type','string'),'ACTIVE',50,'migration'),
('FIELD','followupAt','跟进时间','裁判文书跟进时间','MATTER',json_object('type','string','format','date-time'),'ACTIVE',60,'migration'),
('FIELD','riskFeeAmount','风险代理费','确认的风险代理费金额','MATTER',json_object('type','number'),'ACTIVE',70,'migration'),
('FIELD','collectionResult','催收结果','风险代理费催收处理结果','MATTER',json_object('type','string'),'ACTIVE',80,'migration'),
('FIELD','handoffResult','归档交接结果','纸质或电子档案交接结果','MATTER',json_object('type','string'),'ACTIVE',90,'migration'),
('FIELD','archiveNo','归档编号','档案完成归档后的编号','MATTER',json_object('type','string'),'ACTIVE',100,'migration'),
('MATERIAL','CONTACT_PROOF','联系凭证','通话记录、录音或人工补录凭证','LEAD',json_object(),'ACTIVE',10,'migration'),
('MATERIAL','FOLLOWUP_PROOF','跟进凭证','录音、截图、报价或外访凭证','CUSTOMER',json_object(),'ACTIVE',10,'migration'),
('MATERIAL','CONFLICT_REPORT','冲突审查报告','合同前置冲突审查材料','CONTRACT',json_object(),'ACTIVE',10,'migration'),
('MATERIAL','SIGNED_CONTRACT','已签合同','双方已签署的委托合同','CONTRACT',json_object(),'ACTIVE',20,'migration'),
('MATERIAL','PAYMENT_VOUCHER','收款凭证','银行回单或其他到账凭证','CONTRACT',json_object(),'ACTIVE',30,'migration'),
('MATERIAL','INVOICE_DOCUMENT','发票文件','已开具发票的电子文件','CONTRACT',json_object(),'ACTIVE',40,'migration'),
('MATERIAL','ASSIGNMENT_FORM','分案表','案件分配确认材料','CASE',json_object(),'ACTIVE',10,'migration'),
('MATERIAL','CASE_ACCEPTANCE_FORM','接案确认书','承办律师接案确认材料','CASE',json_object(),'ACTIVE',20,'migration'),
('MATERIAL','TRANSFER_MATERIAL','转案材料','转案原因及交接附件','CASE',json_object(),'ACTIVE',30,'migration'),
('MATERIAL','NODE_MATERIAL','节点材料','事项节点要求的业务材料','MATTER',json_object(),'ACTIVE',10,'migration'),
('MATERIAL','HEARING_MINUTES','庭审笔录','庭审过程和结果记录','MATTER',json_object(),'ACTIVE',20,'migration'),
('MATERIAL','JUDGMENT_FOLLOWUP_PROOF','文书跟进凭证','裁判文书查询和联系凭证','MATTER',json_object(),'ACTIVE',30,'migration'),
('MATERIAL','EXPENSE_VOUCHER','费用凭证','案件费用或报销凭证','MATTER',json_object(),'ACTIVE',40,'migration'),
('MATERIAL','ARCHIVE_HANDOFF_FORM','归档交接表','档案交接确认材料','MATTER',json_object(),'ACTIVE',50,'migration'),
('MATERIAL','ARCHIVE_SCAN','归档扫描件','归档材料电子扫描件','MATTER',json_object(),'ACTIVE',60,'migration'),
('DOD_RECIPE','LEAD_FIRST_CONTACT_READY','首联完成','完成首联并上传联系凭证','LEAD',json_object('requiredFields',json_array('contactResult','contactedAt'),'requiredAttachments',json_array('CONTACT_PROOF'),'validatorRefs',json_array('LeadFirstContactValidator'),'conditionalRules',json_array()),'ACTIVE',10,'migration'),
('DOD_RECIPE','CUSTOMER_PROGRESS_READY','客户跟进完成','记录实质进展并上传跟进凭证','CUSTOMER',json_object('requiredFields',json_array('progressType','progressAt'),'requiredAttachments',json_array('FOLLOWUP_PROOF'),'validatorRefs',json_array(),'conditionalRules',json_array()),'ACTIVE',10,'migration'),
('DOD_RECIPE','CONTRACT_SIGN_READY','合同签署完成','登记签署结果并上传已签合同','CONTRACT',json_object('requiredFields',json_array('contractNo','signedAt','signResult'),'requiredAttachments',json_array('SIGNED_CONTRACT'),'validatorRefs',json_array('ContractTodoValidator'),'conditionalRules',json_array()),'ACTIVE',10,'migration'),
('DOD_RECIPE','CASE_ACCEPT_READY','接案确认完成','记录接案结果并上传确认书','CASE',json_object('requiredFields',json_array('acceptResult'),'requiredAttachments',json_array('CASE_ACCEPTANCE_FORM'),'validatorRefs',json_array('CaseTodoValidator'),'conditionalRules',json_array()),'ACTIVE',10,'migration'),
('DOD_RECIPE','MATTER_ARCHIVE_READY','归档材料齐备','完成归档交接并上传归档材料','MATTER',json_object('requiredFields',json_array('handoffResult','archiveNo'),'requiredAttachments',json_array('ARCHIVE_HANDOFF_FORM','ARCHIVE_SCAN'),'validatorRefs',json_array('ArchiveTodoValidator'),'conditionalRules',json_array()),'ACTIVE',10,'migration');
