<template>
  <config-detail-drawer ref="drawer" :visible="visible" :title="title" size="78%" :dirty="dirty" @update:visible="$emit('update:visible',$event)" @reset="reset">
    <div v-loading="loading" class="template-editor">
      <el-alert v-if="definitionError" :title="definitionError" type="error" :closable="false" show-icon />
      <el-steps :active="activeIndex" finish-status="success" align-center class="step-header">
        <el-step v-for="step in steps" :key="step.name" :title="step.title" @click.native="selectStep(step.name)" />
      </el-steps>
      <template-summary-panel v-if="mode==='view'" :draft="form" :definition-error="definitionError" />
      <template v-else-if="form">
        <template-basic-step v-show="activeStep==='basic'" ref="basic" :value="basicFields" :readonly="publishedReadOnly" :persisted="Boolean(form.templateId)" @input="applyBasicFields" @dirty-change="markDirty" />
        <template-trigger-step v-show="activeStep==='trigger'" ref="trigger" v-model="form.event" :business-type="form.businessType" :readonly="publishedReadOnly" @dirty-change="markDirty" />
        <template-owner-step v-show="activeStep==='owner'" ref="owner" v-model="form.owner.config" :readonly="publishedReadOnly" @dirty-change="markDirty" />
        <template-sla-step v-show="activeStep==='sla'" ref="sla" v-model="form.slaRuleId" :readonly="publishedReadOnly" @dirty-change="markDirty" />
        <template-dod-step v-show="activeStep==='dod'" ref="dod" v-model="form.dodRuleIds" :composition="form.dod.config.composition" :ui-fields="form.ui.config.fields || []" :system-derived-fields="form.dod.config.systemDerivedFields || []" :readonly="publishedReadOnly" @composition-change="setDodComposition" @ui-fields-change="setUiFields" @system-derived-fields-change="setSystemDerivedFields" @dirty-change="markDirty" />
        <template-routing-step v-show="activeStep==='routing'" ref="routing" v-model="form.routing.config" :readonly="publishedReadOnly" :version-id="form.versionId" :versions="versions" :event-type="form.event.eventType" :payload-version="form.event.payloadVersion" @dirty-change="markDirty" />
        <template-preview-step v-show="activeStep==='preview'" ref="preview" :version-id="form.versionId" :event-type="form.event.eventType" :payload-version="form.event.payloadVersion" :business-type="form.businessType" :definition-ready="simulationReady" :source-token="definitionSourceToken()" :definition-hash="preflightGate && preflightGate.hash" />
        <template-version-step v-show="activeStep==='versions'" ref="versions" :versions="versions" />
      </template>
      <el-card v-if="preflightResult" shadow="never" class="preflight-card"><div slot="header">发布预检</div><el-alert :title="preflightPublishable ? '预检通过，可以发布' : '预检未通过，请处理阻断项'" :type="preflightPublishable ? 'success' : 'error'" :closable="false" show-icon /><ul v-if="preflightIssues.length"><li v-for="issue in preflightIssues" :key="`${issue.code}:${issue.path}`">{{ issue.code }} · {{ issue.path }} · {{ issue.message }}</li></ul></el-card>
    </div>
    <template #footer>
      <el-button @click="$refs.drawer.requestProgrammaticClose()">关闭</el-button>
      <el-button v-if="mode!=='view' && activeIndex>0" @click="previous">上一步</el-button>
      <el-button v-if="mode!=='view' && activeIndex<steps.length-1" type="primary" @click="next">下一步</el-button>
      <el-button v-if="!publishedReadOnly" v-hasPermi="['todo:template:edit','todo:template:create','todo:template:copy']" :loading="saving" @click="saveDraft">保存草稿</el-button>
      <el-button v-if="form && form.versionId" v-hasPermi="['todo:release:publish','todo:simulation:simulate']" :loading="preflighting" @click="runPreflight">发布预检</el-button>
      <el-button v-if="canPublishDraft" v-hasPermi="['todo:release:publish']" type="success" :loading="publishing" @click="publish">发布</el-button>
    </template>
  </config-detail-drawer>
</template>

<script>
import ConfigDetailDrawer from '../shared/ConfigDetailDrawer'
import TemplateSummaryPanel from './TemplateSummaryPanel'
import TemplateBasicStep from './steps/TemplateBasicStep'
import TemplateTriggerStep from './steps/TemplateTriggerStep'
import TemplateOwnerStep from './steps/TemplateOwnerStep'
import TemplateSlaStep from './steps/TemplateSlaStep'
import TemplateDodStep from './steps/TemplateDodStep'
import TemplateRoutingStep from './steps/TemplateRoutingStep'
import TemplatePreviewStep from './steps/TemplatePreviewStep'
import TemplateVersionStep from './steps/TemplateVersionStep'
import { createTodoTemplate, copyTodoTemplate, getTodoTemplate, updateTodoTemplate, updateTemplateDraft, listTemplateVersions, preflightTemplateDraft, publishReleaseRecord } from '@/api/todo-config'
import { emptyDraft, hydrateTemplateDraft, toTemplateDraftPayload, createPreflightGate, canPublishFromGate, invalidatePreflightGate, mergeCreatedAggregate } from './template-draft-model'

export default {
  name: 'TemplateDrawer', components: { ConfigDetailDrawer, TemplateSummaryPanel, TemplateBasicStep, TemplateTriggerStep, TemplateOwnerStep, TemplateSlaStep, TemplateDodStep, TemplateRoutingStep, TemplatePreviewStep, TemplateVersionStep },
  props: { visible: Boolean, detail: { type: Object, default: null }, mode: { type: String, default: 'view' }, initialStep: { type: String, default: 'basic' } },
  data() { return { steps: [{ name: 'basic', title: '基础信息' }, { name: 'trigger', title: '触发条件' }, { name: 'owner', title: '负责人' }, { name: 'sla', title: 'SLA' }, { name: 'dod', title: '完成条件' }, { name: 'routing', title: '路由' }, { name: 'preview', title: '模拟' }, { name: 'versions', title: '版本' }], activeStep: 'basic', form: emptyDraft(), versions: [], loading: false, saving: false, preflighting: false, publishing: false, dirty: false, hydrating: false, definitionError: '', preflightResult: null, preflightGate: null, sourceTemplateId: null, savedMetadata: null } },
  computed: { title() { const labels = { create: '新建待办模板', edit: '编辑待办模板', copy: '复制待办模板', view: '待办模板详情', simulate: '模板模拟', publish: '模板发布' }; return labels[this.mode] || '待办模板' }, activeIndex() { return Math.max(0, this.steps.findIndex(item => item.name === this.activeStep)) }, basicFields() { const keys = ['templateCode','templateName','businessType','businessStage','templateType','priority','changeSummary','impactScope','description']; return keys.reduce((result, key) => { result[key] = this.form ? this.form[key] : ''; return result }, {}) }, publishedReadOnly() { return Boolean(this.definitionError) || ['view','simulate','publish'].includes(this.mode) || (this.form && this.form.versionId && this.form.versionStatus !== 'DRAFT') }, canPublishDraft() { return !this.definitionError && this.mode !== 'view' && this.mode !== 'simulate' && this.form && this.form.versionId && this.form.versionStatus === 'DRAFT' }, preflightIssues() { const report = this.preflightResult && this.preflightResult.report; return report && Array.isArray(report.errors) ? report.errors : [] }, preflightPublishable() { return Boolean(this.preflightResult && this.preflightResult.report && this.preflightIssues.length === 0) }, simulationReady() { return canPublishFromGate(this.preflightGate, this.form.versionId, this.definitionSourceToken(), this.dirty) } },
  watch: { visible(value) { if (value) this.open() }, detail() { if (this.visible) this.open() } },
  methods: {
    actionId(action) { return `template-${action}-${Date.now()}-${Math.random().toString(16).slice(2)}` }, definitionSourceToken() { return this.form ? this.form.sourceDefinitionJson : null },
    async open() { this.loading = true; this.definitionError = ''; this.preflightResult = null; this.preflightGate = invalidatePreflightGate(); this.activeStep = this.initialStep || 'basic'; try { if (this.mode === 'create') this.hydrateEmpty(); else if (this.mode === 'copy') this.hydrateCopy(this.detail); else await this.refreshSavedDraft(this.detail && (this.detail.templateId || this.detail.template_id)) } finally { this.loading = false } },
    metadataSnapshot() { return this.form ? { templateName: this.form.templateName } : null }, metadataChanged() { return this.savedMetadata && JSON.stringify(this.savedMetadata) !== JSON.stringify(this.metadataSnapshot()) },
    applyBasicFields(value) { Object.keys(value || {}).forEach(key => { this.$set(this.form, key, value[key]) }) },
    hydrateEmpty() { this.hydrating = true; this.form = emptyDraft(); this.versions = []; this.sourceTemplateId = null; this.savedMetadata = null; this.dirty = false; this.$nextTick(() => { this.hydrating = false }) },
    hydrateCopy(detail) { this.sourceTemplateId = detail && (detail.templateId || detail.template_id); try { this.hydrating = true; this.form = hydrateTemplateDraft(detail || {}); this.form.templateId = null; this.form.versionId = null; this.form.templateCode = `${this.form.templateCode}_COPY`; this.form.templateName = `${this.form.templateName}（复制）`; this.form.versionStatus = 'DRAFT'; this.form.sourceDefinitionJson = null; this.versions = []; this.dirty = true } catch (error) { this.failClosed(error) } finally { this.$nextTick(() => { this.hydrating = false }) } },
    failClosed(error) { const code = error && error.code; this.definitionError = code === 'TODO_DEFINITION_CANONICAL_INVALID' ? 'TODO_DEFINITION_CANONICAL_INVALID：服务端保存的规范定义 JSON 已损坏。' : ((error && error.message) || '模板定义加载失败'); this.form = emptyDraft(); this.dirty = false },
    async refreshSavedDraft(templateId) { if (!templateId) return this.hydrateEmpty(); const responses = await Promise.all([getTodoTemplate(templateId), listTemplateVersions(templateId)]); try { this.hydrating = true; this.form = hydrateTemplateDraft(responses[0].data || {}); this.versions = responses[1].data || []; this.sourceTemplateId = templateId; this.savedMetadata = this.metadataSnapshot(); this.definitionError = ''; this.dirty = false } catch (error) { this.failClosed(error) } finally { this.$nextTick(() => { this.hydrating = false }) } },
    markDirty() { if (!this.hydrating) { this.dirty = true; this.preflightGate = invalidatePreflightGate() } }, setDodComposition(value) { this.$set(this.form.dod.config, 'composition', value); this.markDirty() }, setUiFields(value) { this.$set(this.form.ui.config, 'fields', (value || []).slice()); this.markDirty() }, setSystemDerivedFields(value) { this.$set(this.form.dod.config, 'systemDerivedFields', (value || []).slice()); this.markDirty() }, selectStep(name) { this.activeStep = name }, previous() { this.activeStep = this.steps[Math.max(0, this.activeIndex - 1)].name }, async next() { const valid = await this.validateCurrentStep(); if (valid) this.activeStep = this.steps[Math.min(this.steps.length - 1, this.activeIndex + 1)].name },
    async validateCurrentStep() { const ref = this.$refs[this.activeStep]; return !ref || !ref.validate ? true : Boolean(await ref.validate()) },
    async validateAllSteps() { for (const step of this.steps.slice(0, 6)) { const ref = this.$refs[step.name]; if (ref && ref.validate && !(await ref.validate())) { this.activeStep = step.name; return false } } return true },
    async ensureAggregate() { if (this.form.versionId) return; const unsaved = JSON.parse(JSON.stringify(this.form)); let response; if (this.mode === 'copy') response = await copyTodoTemplate(this.sourceTemplateId, { actionId: this.actionId('copy'), newTemplateCode: unsaved.templateCode, newTemplateName: unsaved.templateName }); else response = await createTodoTemplate({ actionId: this.actionId('create'), templateCode: unsaved.templateCode, templateName: unsaved.templateName, businessType: unsaved.businessType }); const result = response.data || {}; const responses = await Promise.all([getTodoTemplate(result.templateId), listTemplateVersions(result.templateId)]); const persisted = hydrateTemplateDraft(responses[0].data || {}); this.form = mergeCreatedAggregate(unsaved, result, persisted); this.versions = responses[1].data || []; this.sourceTemplateId = result.templateId; this.savedMetadata = this.metadataSnapshot(); this.dirty = true },
    async saveDraft() { if (!(await this.validateCurrentStep())) return false; this.saving = true; try { await this.ensureAggregate(); if (this.metadataChanged()) { await updateTodoTemplate(this.form.templateId, { templateId: this.form.templateId, templateName: this.form.templateName, actionId: this.actionId('metadata'), expectedVersion: Number(this.form.templateVersion || 0) }); this.form.templateVersion = Number(this.form.templateVersion || 0) + 1; this.savedMetadata = this.metadataSnapshot() } const payload = toTemplateDraftPayload(this.form, this.actionId('save-draft')); payload.expectedDefinitionJson = this.form.sourceDefinitionJson; payload.ruleReferences = payload.ruleReferences || []; payload.changeSummary = this.form.changeSummary || ''; payload.impactScope = this.form.impactScope || ''; await updateTemplateDraft(this.form.versionId, payload); await this.refreshSavedDraft(this.form.templateId); this.$modal.msgSuccess('模板草稿已保存'); this.$emit('saved', this.form.templateId); return true } catch (error) { if (this.form.templateId) await this.refreshSavedDraft(this.form.templateId).catch(() => undefined); this.$modal.msgError((error && (error.msg || error.message)) || '保存模板草稿失败'); return false } finally { this.saving = false } },
    async runPreflight() { if (this.dirty && !(await this.saveDraft())) return false; this.preflighting = true; try { const response = await preflightTemplateDraft(this.form.versionId); this.preflightResult = response.data || {}; const report = this.preflightResult.report || {}; await this.refreshSavedDraft(this.form.templateId); this.preflightGate = createPreflightGate(this.form.versionId, this.definitionSourceToken(), report.definitionHash); if (!this.preflightPublishable) { this.$modal.msgError('发布预检未通过'); return false } this.$modal.msgSuccess('发布预检通过'); return true } catch (error) { this.preflightGate = invalidatePreflightGate(); this.$modal.msgError((error && (error.msg || error.message)) || '发布预检失败'); return false } finally { this.preflighting = false } },
    async publish() { if (!(await this.validateAllSteps())) return; if (this.dirty && !(await this.saveDraft())) return; if (!canPublishFromGate(this.preflightGate, this.form.versionId, this.definitionSourceToken(), this.dirty) && !(await this.runPreflight())) return; if (!canPublishFromGate(this.preflightGate, this.form.versionId, this.definitionSourceToken(), this.dirty)) return; this.publishing = true; try { await publishReleaseRecord(this.form.versionId, { actionId: this.actionId('publish'), versionId: this.form.versionId, expectedDefinitionHash: this.preflightGate.hash }); this.$modal.msgSuccess('模板已发布'); this.$emit('published', this.form.templateId); await this.refreshSavedDraft(this.form.templateId) } catch (error) { this.$modal.msgError((error && (error.msg || error.message)) || '发布失败') } finally { this.publishing = false } },
    reset() { this.form = emptyDraft(); this.versions = []; this.dirty = false; this.definitionError = ''; this.preflightResult = null; this.preflightGate = invalidatePreflightGate() }
  }
}
</script>
<style scoped lang="scss">@import '../styles/config-center.scss';.template-editor{padding:0 22px 24px}.step-header{margin:4px 0 26px}.preflight-card{margin-top:16px}.preflight-card ul{margin:12px 0 0;padding-left:22px;color:#b91c1c}</style>
