package com.law.todo.mapper;

import java.util.List;
import java.util.Map;
import java.time.LocalDateTime;
import org.apache.ibatis.annotations.Param;
import com.law.todo.domain.model.TodoInstance;

public interface TodoMapper
{
    int insertInstance(TodoInstance value);
    TodoInstance selectById(Long todoId);
    TodoInstance selectByTriggerKey(String key);
    TodoInstance selectByNextKey(String key);
    int updateStatusConditionally(@Param("todoId") Long todoId,@Param("fromStatus") String fromStatus,@Param("toStatus") String toStatus,@Param("ownerId") Long ownerId,@Param("operator") String operator);
    int insertActionIfAbsent(Map<String,Object> action);
    Map<String,Object> selectActionById(String actionId);
    int insertCandidate(Map<String,Object> candidate);
    List<Map<String,Object>> selectCandidates(Long todoId);
    int insertRelation(Map<String,Object> relation);
    Map<String,Object> selectTemplateVersion(@Param("templateId") Long templateId,@Param("versionNo") int versionNo);
    int insertTemplateVersion(Map<String,Object> version);
    int updateTemplateCurrentVersion(@Param("templateId") Long templateId,@Param("versionNo") int versionNo,@Param("operator") String operator);
    List<Map<String,Object>> selectTriggerRules(@Param("eventType") String eventType,@Param("businessType") String businessType);
    List<Map<String,Object>> selectSlaScanItems(@Param("now") LocalDateTime now);
    int markSlaThreshold(@Param("todoId") Long todoId,@Param("threshold") String threshold,@Param("now") LocalDateTime now);
    int pauseSla(@Param("todoId") Long todoId,@Param("now") LocalDateTime now);
    int resumeSla(@Param("todoId") Long todoId,@Param("now") LocalDateTime now);
    Map<String,Object> selectDashboard(@Param("userId") Long userId,@Param("deptId") Long deptId);
    List<Map<String,Object>> selectTodoList(Map<String,Object> query);
    Map<String,Object> selectTemplateVersionById(Long versionId);
    List<String> selectAttachmentTypes(Long todoId);
    int insertAttachment(Map<String,Object> attachment);
    int insertCc(@Param("todoId") Long todoId,@Param("userId") Long userId,@Param("ccType") String ccType);
    List<Map<String,Object>> selectCalendars();
    int insertCalendar(Map<String,Object> calendar);
    int updateCalendar(Map<String,Object> calendar);
    Map<String,Object> selectCalendarByCode(String code);
    int insertSlaRecord(Map<String,Object> record);
    int insertSlaNotification(@Param("todoId") Long todoId,@Param("notificationType") String notificationType,@Param("now") LocalDateTime now);
    int insertSupervisorEscalationNotification(@Param("todoId") Long todoId,@Param("now") LocalDateTime now);
    int countCandidateAccess(@Param("todoId") Long todoId,@Param("userId") Long userId,@Param("deptId") Long deptId);
    int countCcAccess(@Param("todoId") Long todoId,@Param("userId") Long userId);
    int countSupervisorAccess(@Param("todoId") Long todoId,@Param("userId") Long userId);
    Long selectUserDeptId(Long userId);
    List<Map<String,Object>> selectTemplates();
    int insertTemplate(Map<String,Object> value);
    int updateTemplate(Map<String,Object> value);
    List<Map<String,Object>> selectAllTriggerRules();
    int insertTriggerRule(Map<String,Object> value);
    int updateTriggerRule(Map<String,Object> value);
    List<Map<String,Object>> selectActionTimeline(Long todoId);
    List<Map<String,Object>> selectAttachments(Long todoId);
    List<Map<String,Object>> selectCc(Long todoId);
    List<Map<String,Object>> selectRelations(Long todoId);
    List<Map<String,Object>> selectNotifications(@Param("userId") Long userId,@Param("status") String status);
    int markNotificationRead(@Param("notificationId") Long notificationId,@Param("userId") Long userId);
    Map<String,Object> selectTemplateById(Long templateId);
    List<Map<String,Object>> selectTemplateVersions(Long templateId);
    int updateTemplateVersionDraft(Map<String,Object> version);
    int publishTemplateVersionConditionally(@Param("versionId") Long versionId,@Param("operator") String operator);
    int insertDefinitionActionIfAbsent(Map<String,Object> action);
    Map<String,Object> selectDefinitionActionById(String actionId);
    int updateDefinitionActionEntity(@Param("actionId") String actionId,@Param("entityId") Long entityId);
    Map<String,Object> selectBusinessTodoSummary(Map<String,Object> query);
    List<Long> selectBusinessTodoOwners(Map<String,Object> query);
    Map<String,Object> selectBusinessRecentAction(Map<String,Object> query);
    List<Map<String,Object>> selectBusinessTodos(Map<String,Object> query);
    Map<String,Object> selectRootTodo(Long rootTodoId);
    List<Map<String,Object>> selectTodoChain(Map<String,Object> query);
}
