package com.law.business.event;

public enum BusinessEventType
{
    LEAD_CREATED,
    LEAD_ASSIGNED,
    LEAD_MOVED_TO_POOL,
    LEAD_CLAIMED,
    LEAD_CONVERTED,
    CONTRACT_SUBMITTED,
    CONTRACT_APPROVED,
    CONTRACT_SIGNED,
    PAYMENT_CONFIRMED,
    PAYMENT_REJECTED,
    INVOICE_HANDLED,
    CASE_CREATED,
    CASE_ASSIGNED,
    CASE_ACCEPTED,
    CASE_REJECTED,
    CASE_TRANSFER_REQUESTED,
    CASE_TRANSFER_APPROVED,
    ARCHIVE_APPLIED,
    CASE_CLOSED,
    CASE_ARCHIVED
}
