package com.ruoyi.system.foundation;

public enum FoundationTestIdentityErrorCode
{
    FOUNDATION_TEST_IDENTITIES_PROFILE_FORBIDDEN,
    FOUNDATION_TEST_IDENTITIES_PASSWORD_REQUIRED,
    FOUNDATION_TEST_IDENTITIES_PASSWORD_WEAK,
    FOUNDATION_TEST_IDENTITIES_ROLE_MISSING,
    FOUNDATION_TEST_IDENTITIES_ROLE_MISMATCH,
    FOUNDATION_TEST_IDENTITIES_USER_CONFLICT,
    FOUNDATION_TEST_IDENTITIES_DEPARTMENT_CONFLICT
}
