<template><div class="biz-page todo-page" :class="'biz-size-'+appSize">
  <biz-page-header title="待办中心" description="统一处理责任、完成条件和时限升级"/>
  <section class="todo-metrics"><todo-summary-card :value="dashboard.mine" label="我的待办" hint="当前需要处理" icon="el-icon-user"/><todo-summary-card :value="dashboard.candidate" label="候选池" hint="可以领取的工作" icon="el-icon-collection"/><todo-summary-card :value="dashboard.overdue" label="超时待办" hint="需要优先处理" icon="el-icon-alarm-clock"/></section>
  <biz-table-card :show-search.sync="showSearch" :total="total" :page.sync="query.pageNum" :limit.sync="query.pageSize" @query="search" @pagination="load">
    <template slot="filters"><div class="biz-filter-main"><el-radio-group v-model="query.mode" :size="controlSize" @change="search"><el-radio-button label="mine">我的</el-radio-button><el-radio-button label="candidate">候选池</el-radio-button><el-radio-button label="overdue">超时</el-radio-button><el-radio-button label="visible">可见</el-radio-button><el-radio-button label="dept">本部门</el-radio-button><el-radio-button label="cc">抄送我</el-radio-button></el-radio-group><el-input v-model="query.keyword" :size="controlSize" clearable placeholder="搜索标题或业务编号" @keyup.enter.native="search"/><el-select v-model="query.status" clearable placeholder="状态" @change="search"><el-option v-for="s in dict.type.law_todo_status" :key="s.value" :label="s.label" :value="s.value"/></el-select></div></template>
    <el-table v-loading="loading" :data="rows"><el-table-column label="待办编号" prop="todo_no" width="160"/><el-table-column label="标题" min-width="210"><template slot-scope="{row}"><el-button type="text" @click="openDetail(row)">{{ row.title }}</el-button><small>{{ row.business_no||'-' }}</small></template></el-table-column><el-table-column label="状态" width="110"><template slot-scope="{row}"><dict-tag :options="dict.type.law_todo_status" :value="row.status"/></template></el-table-column><el-table-column label="SLA" width="110"><template slot-scope="{row}"><dict-tag :options="dict.type.law_todo_sla_status" :value="row.sla_status"/></template></el-table-column><el-table-column label="截止时间" prop="due_at" width="170"/><el-table-column label="操作" width="330" fixed="right"><template slot-scope="{row}"><el-button v-if="row.status==='CREATED'" v-hasPermi="['todo:claim']" type="text" @click="openAction(row,'claim')">领取</el-button><el-button v-if="['CLAIMED','RETURNED'].includes(row.status)" v-hasPermi="['todo:start']" type="text" @click="openAction(row,'start')">开始</el-button><el-button v-if="row.status==='IN_PROGRESS'" v-hasPermi="['todo:submit']" type="text" @click="openAction(row,'submit')">提交</el-button><el-button v-if="row.status==='SUBMITTED'" v-hasPermi="['todo:complete']" type="text" @click="openAction(row,'complete')">完成</el-button><el-button v-if="row.status==='SUBMITTED'" v-hasPermi="['todo:return']" type="text" @click="openAction(row,'return')">退回</el-button><el-button v-hasPermi="['todo:transfer']" type="text" @click="openAction(row,'transfer')">转派</el-button><el-button v-hasPermi="['todo:chain:query']" type="text" @click="openChain(row)">链路</el-button></template></el-table-column></el-table>
  </biz-table-card>
  <todo-detail-drawer :visible.sync="detailOpen" :detail="detail" @extension-requested="refresh"/><todo-action-dialogs :visible.sync="actionOpen" :action="action" :todo="selected" :submitting="submitting" @submit="execute"/>
  <el-drawer title="待办全链路" :visible.sync="chainOpen" size="620px"><div class="chain-body"><todo-chain-timeline :nodes="chainNodes"/></div></el-drawer>
</div></template>
<script>
import businessUi from '@/views/business/mixins/businessUi';import BizPageHeader from '@/views/business/components/BizPageHeader';import BizTableCard from '@/views/business/components/BizTableCard';import TodoSummaryCard from './components/TodoSummaryCard';import TodoDetailDrawer from './components/TodoDetailDrawer';import TodoActionDialogs from './components/TodoActionDialogs';import TodoChainTimeline from './components/TodoChainTimeline';import {getTodoDashboard,listTodo,getTodo,getTodoChain,claimTodo,startTodo,submitTodo,completeTodo,returnTodo,transferTodo,cancelTodo} from '@/api/todo';
const actions={claim:claimTodo,start:startTodo,submit:submitTodo,complete:completeTodo,return:returnTodo,transfer:transferTodo,cancel:cancelTodo}
export default{name:'TodoCenter',dicts:['law_todo_status','law_todo_priority','law_todo_sla_status'],mixins:[businessUi],components:{BizPageHeader,BizTableCard,TodoSummaryCard,TodoDetailDrawer,TodoActionDialogs,TodoChainTimeline},data(){return{showSearch:true,loading:false,submitting:false,total:0,rows:[],dashboard:{mine:0,candidate:0,overdue:0},query:{pageNum:1,pageSize:10,mode:'mine',keyword:'',status:''},detailOpen:false,detail:{},actionOpen:false,action:'',selected:null,chainOpen:false,chainNodes:[]}},created(){this.refresh()},methods:{refresh(){getTodoDashboard().then(r=>{this.dashboard=r.data||{}});this.load()},load(){this.loading=true;listTodo(this.query).then(r=>{this.rows=r.rows||[];this.total=r.total||0}).finally(()=>{this.loading=false})},search(){this.query.pageNum=1;this.load()},openDetail(row){getTodo(row.todo_id).then(r=>{this.detail=r.data||{};this.detailOpen=true})},openChain(row){getTodoChain(row.root_todo_id||row.todo_id).then(r=>{this.chainNodes=(r.data&&r.data.nodes)||[];this.chainOpen=true})},openAction(row,action){this.selected=row;this.action=action;this.actionOpen=true},execute(form){this.submitting=true;const data={actionId:`web-${Date.now()}-${Math.random().toString(16).slice(2)}`,opinion:form.opinion,fields:form.fields,fileObjectIds:form.fileObjectIds};actions[this.action](this.selected.todo_id,data).then(()=>{this.$modal.msgSuccess('处理成功');this.actionOpen=false;this.refresh()}).finally(()=>{this.submitting=false})}}}
</script><style scoped lang="scss">@import "../business/business.scss";.todo-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:14px 0}.biz-filter-main{display:flex;gap:10px;flex-wrap:wrap}.el-button+small{display:block;color:#64748b}.chain-body{padding:18px}@media(max-width:768px){.todo-metrics{grid-template-columns:1fr}}</style>
