<template>
  <config-detail-drawer ref="drawer" :visible="visible" :title="drawerTitle" size="760px" :dirty="isDirty" @update:visible="$emit('update:visible', $event)" @reset="reset">
    <el-form ref="form" :model="form" :rules="rules" label-width="126px" class="rule-drawer-form">
      <el-collapse v-model="sections">
        <el-collapse-item title="基本信息" name="basic">
          <el-row :gutter="16"><el-col :span="12"><el-form-item label="规则编码" prop="ruleCode"><el-input v-model.trim="form.ruleCode" :disabled="readonly || persisted" maxlength="64" /></el-form-item></el-col><el-col :span="12"><el-form-item label="规则名称" prop="ruleName"><el-input v-model.trim="form.ruleName" :disabled="readonly || copyMode" maxlength="128" /></el-form-item></el-col></el-row>
          <el-row :gutter="16"><el-col :span="12"><el-form-item label="规则类型" prop="ruleType"><el-select v-model="form.ruleType" :disabled="readonly || copyMode" class="full-width"><el-option v-for="item in dict.type.law_todo_dod_rule_type" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="状态" prop="status"><el-input v-if="persisted && !copyMode" :value="statusLabel" disabled /><el-select v-else v-model="form.status" :disabled="readonly || copyMode" class="full-width"><el-option v-for="item in dict.type.law_todo_rule_status" :key="item.value" :label="item.label" :value="item.value" /></el-select><p v-if="persisted && !copyMode" class="status-note">已保存规则的状态仅可通过“启用/停用”操作修改。</p></el-form-item></el-col></el-row>
        </el-collapse-item>
        <el-collapse-item title="必填字段" name="fields"><template v-if="!malformed.requiredFieldsJson"><el-form-item label="稳定字段编码"><el-select v-model="form.requiredFields" multiple filterable allow-create default-first-option :disabled="readonly || copyMode" placeholder="输入稳定字段编码后回车" class="full-width"><el-option v-for="item in form.requiredFields" :key="item" :label="item" :value="item" /></el-select></el-form-item><p class="drawer-note">字段编码是业务数据，不是固定选项；请使用稳定、可复用的编码。</p></template><malformed-json-editor v-else field-label="requiredFieldsJson" :value.sync="raw.requiredFieldsJson" :disabled="readonly || copyMode" @repaired="repairArray('requiredFieldsJson', $event)" /></el-collapse-item>
        <el-collapse-item title="必需材料类型" name="attachments"><template v-if="!malformed.requiredAttachmentsJson"><el-form-item label="材料类型编码"><el-select v-model="form.requiredAttachments" multiple filterable allow-create default-first-option :disabled="readonly || copyMode" placeholder="输入材料类型编码后回车" class="full-width"><el-option v-for="item in form.requiredAttachments" :key="item" :label="item" :value="item" /></el-select></el-form-item></template><malformed-json-editor v-else field-label="requiredAttachmentsJson" :value.sync="raw.requiredAttachmentsJson" :disabled="readonly || copyMode" @repaired="repairArray('requiredAttachmentsJson', $event)" /></el-collapse-item>
        <el-collapse-item title="条件必填要求" name="conditions"><template v-if="!malformed.conditionalRulesJson"><div v-for="(condition, index) in form.conditionalRules" :key="index" class="condition-row"><el-input v-model.trim="condition.field" :disabled="readonly || copyMode" placeholder="需要补充的字段编码"/><span>当</span><el-input v-model.trim="condition.when.field" :disabled="readonly || copyMode" placeholder="条件字段编码"/><el-select v-model="condition.when.kind" :disabled="readonly || copyMode" class="condition-kind"><el-option label="等于" value="equals"/><el-option label="存在" value="present"/></el-select><el-input v-if="condition.when.kind === 'equals'" v-model="condition.when.value" :disabled="readonly || copyMode" placeholder="期望值"/><el-switch v-else v-model="condition.when.value" :disabled="readonly || copyMode" active-text="存在" inactive-text="不存在"/><el-button v-if="!readonly && !copyMode" type="text" class="danger-text" @click="removeCondition(index)">删除</el-button></div><el-button v-if="!readonly && !copyMode" plain icon="el-icon-plus" @click="addCondition">添加条件</el-button></template><malformed-json-editor v-else field-label="conditionalRulesJson" :value.sync="raw.conditionalRulesJson" :disabled="readonly || copyMode" @repaired="repairConditions" /></el-collapse-item>
        <el-collapse-item title="服务端校验器" name="validators"><template v-if="!malformed.validatorRefsJson"><el-form-item label="校验器目录"><el-select v-model="form.validatorRefs" multiple filterable :disabled="readonly || copyMode" placeholder="选择已注册的服务端校验器" class="full-width"><el-option v-for="validator in validatorCatalog" :key="validator.code" :label="validatorLabel(validator)" :value="validator.code" /></el-select></el-form-item><p class="drawer-note">目录来自后端能力注册；规则不能引用未注册的校验器。</p></template><malformed-json-editor v-else field-label="validatorRefsJson" :value.sync="raw.validatorRefsJson" :disabled="readonly || copyMode" @repaired="repairArray('validatorRefsJson', $event)" /></el-collapse-item>
        <el-collapse-item title="错误文案映射" name="messages"><template v-if="!malformed.errorMessagesJson"><div v-for="(item, index) in form.errorMessages" :key="index" class="message-row"><el-input v-model.trim="item.key" :disabled="readonly || copyMode" placeholder="字段或错误编码"/><el-input v-model.trim="item.message" :disabled="readonly || copyMode" placeholder="面向用户的错误文案"/><el-button v-if="!readonly && !copyMode" type="text" class="danger-text" @click="removeMessage(index)">删除</el-button></div><el-button v-if="!readonly && !copyMode" plain icon="el-icon-plus" @click="addMessage">添加映射</el-button></template><malformed-json-editor v-else field-label="errorMessagesJson" :value.sync="raw.errorMessagesJson" :disabled="readonly || copyMode" @repaired="repairMessages" /></el-collapse-item>
        <el-collapse-item title="绑定与引用" name="binding"><el-descriptions :column="2" border size="small"><el-descriptions-item label="模板引用数">{{ form.referenceCount || 0 }}</el-descriptions-item><el-descriptions-item label="版本">{{ form.version }}</el-descriptions-item><el-descriptions-item label="最后更新">{{ format(form.updateTime) }}</el-descriptions-item><el-descriptions-item label="更新人">{{ form.updateBy || '-' }}</el-descriptions-item></el-descriptions></el-collapse-item>
        <el-collapse-item title="样例验证" name="test"><el-form-item label="样例 payload"><el-input v-model.trim="samplePayloadText" type="textarea" :rows="4" :disabled="!persisted || testing" placeholder='例如 {"result":"ok"}' /></el-form-item><el-form-item label="样例材料编码"><el-select v-model="sampleAttachments" multiple filterable allow-create default-first-option :disabled="!persisted || testing" placeholder="输入材料类型编码后回车" class="full-width"><el-option v-for="item in sampleAttachments" :key="item" :label="item" :value="item" /></el-select></el-form-item><el-button v-if="persisted" v-hasPermi="['todo:dod-rule:list']" :loading="testing" @click="runTest">执行样例验证</el-button><p v-else class="drawer-note">请先保存规则，再调用后端校验器进行样例验证。</p><section v-if="testResult" class="test-result"><el-alert :title="testResult.passed ? '样例满足全部完成条件' : '样例未满足完成条件'" :type="testResult.passed ? 'success' : 'warning'" :closable="false" show-icon /><div v-if="testResult.missingFields && testResult.missingFields.length"><strong>缺少字段</strong><ul><li v-for="item in testResult.missingFields" :key="`field-${item}`">{{ item }}</li></ul></div><div v-if="testResult.missingAttachments && testResult.missingAttachments.length"><strong>缺少材料</strong><ul><li v-for="item in testResult.missingAttachments" :key="`attachment-${item}`">{{ item }}</li></ul></div><div v-if="testResult.validatorIssues && testResult.validatorIssues.length"><strong>校验器问题</strong><ul><li v-for="(item, index) in testResult.validatorIssues" :key="`validator-${index}`">{{ issueText(item) }}</li></ul></div></section></el-collapse-item>
      </el-collapse>
    </el-form>
    <template #footer><el-button :disabled="saving || copying || toggling || testing" @click="$refs.drawer.requestProgrammaticClose()">取消</el-button><el-button v-if="persisted && !copyMode" v-hasPermi="['todo:dod-rule:toggle']" :loading="toggling" :type="form.status === '0' ? 'warning' : 'success'" @click="toggle">{{ form.status === '0' ? '停用规则' : '启用规则' }}</el-button><el-button v-if="persisted && !copyMode" v-hasPermi="['todo:dod-rule:copy']" @click="$emit('copy', form)">复制</el-button><el-button v-if="readonly" v-hasPermi="['todo:dod-rule:edit']" type="primary" @click="$emit('edit', form)">编辑</el-button><el-button v-else-if="copyMode" v-hasPermi="['todo:dod-rule:copy']" type="primary" :loading="copying" @click="saveCopy">创建副本</el-button><el-button v-else v-hasPermi="[persisted ? 'todo:dod-rule:edit' : 'todo:dod-rule:create']" type="primary" :loading="saving" :disabled="hasMalformedStoredJson" @click="save">保存</el-button></template>
  </config-detail-drawer>
</template>

<script>
import ConfigDetailDrawer from '../shared/ConfigDetailDrawer'
import { listTodoValidatorCatalog } from '@/api/todo-definition'
import { createDodRule, updateDodRule, copyDodRule, toggleDodRule, getDodRuleReferenceCount, testDodRule } from '@/api/todo-config'

const emptyForm = () => ({ dodRuleId: null, ruleCode: '', ruleName: '', ruleType: '', requiredFields: [], requiredAttachments: [], conditionalRules: [], validatorRefs: [], errorMessages: [], status: '0', serverStatus: '0', version: 0, referenceCount: 0, updateTime: '', updateBy: '' })
const valueOf = (row, camel, snake) => row && (row[camel] !== undefined ? row[camel] : row[snake])
const parseJson = (value, fallback) => { if (value === null || value === undefined || value === '') return { value: fallback, raw: JSON.stringify(fallback), malformed: false }; try { const parsed = typeof value === 'string' ? JSON.parse(value) : value; return { value: parsed, raw: JSON.stringify(parsed), malformed: false } } catch (error) { return { value: fallback, raw: String(value), malformed: true } } }
const MalformedJsonEditor = { name: 'MalformedJsonEditor', props: { fieldLabel: String, value: String, disabled: Boolean }, methods: { attemptRepair() { try { const parsed = JSON.parse(this.value); this.$emit('repaired', parsed) } catch (error) { this.$modal.msgError(`${this.fieldLabel} 仍不是合法 JSON`) } } }, template: '<div class="malformed-editor"><el-alert :title="fieldLabel + \" 存储内容格式异常；已保留原文，修复后才允许保存\"" type="error" :closable="false" show-icon /><el-input :value="value" type="textarea" :rows="5" :disabled="disabled" @input="$emit(\"update:value\", $event)" /><el-button v-if="!disabled" type="primary" plain size="mini" @click="attemptRepair">验证并修复</el-button></div>' }
export default {
  name: 'DodRuleDrawer', components: { ConfigDetailDrawer, MalformedJsonEditor },
  dicts: ['law_todo_dod_rule_type', 'law_todo_rule_status'],
  props: { visible: Boolean, rule: { type: Object, default: null }, mode: { type: String, default: 'view' } },
  data() { return { form: emptyForm(), raw: { requiredFieldsJson: '[]', requiredAttachmentsJson: '[]', conditionalRulesJson: '[]', validatorRefsJson: '[]', errorMessagesJson: '{}' }, malformed: { requiredFieldsJson: false, requiredAttachmentsJson: false, conditionalRulesJson: false, validatorRefsJson: false, errorMessagesJson: false }, validatorCatalog: [], sections: ['basic', 'fields', 'attachments', 'conditions'], initialSnapshot: '', samplePayloadText: '{}', sampleAttachments: [], testResult: null, saving: false, copying: false, toggling: false, testing: false, rules: { ruleCode: [{ required: true, message: '请输入规则编码', trigger: 'blur' }], ruleName: [{ required: true, message: '请输入规则名称', trigger: 'blur' }], ruleType: [{ required: true, message: '请选择规则类型', trigger: 'change' }] } } },
  computed: { persisted() { return Boolean(this.form.dodRuleId) }, readonly() { return this.mode === 'view' }, copyMode() { return this.mode === 'copy' }, drawerTitle() { return ({ create: '新增完成条件规则', edit: '编辑完成条件规则', copy: '复制完成条件规则', view: '完成条件规则详情' })[this.mode] || '完成条件规则' }, statusLabel() { const item = (this.dict.type.law_todo_rule_status || []).find(option => option.value === this.form.serverStatus); return item ? item.label : this.form.serverStatus }, hasMalformedStoredJson() { return Object.values(this.malformed).some(Boolean) }, isDirty() { return !this.readonly && this.initialSnapshot && this.snapshot() !== this.initialSnapshot } },
  watch: { visible(open) { if (open) this.hydrate() }, rule() { if (this.visible) this.hydrate() } }, created() { this.loadValidators() },
  methods: {
    loadValidators() { return listTodoValidatorCatalog().then(response => { this.validatorCatalog = response.data || [] }).catch(() => { this.validatorCatalog = [] }) },
    hydrate() { const source = this.rule || {}; const form = emptyForm(); ['dodRuleId', 'ruleCode', 'ruleName', 'ruleType', 'status', 'version', 'referenceCount', 'updateTime', 'updateBy'].forEach(key => { const snake = key.replace(/[A-Z]/g, item => `_${item.toLowerCase()}`); const value = valueOf(source, key, snake); if (value !== undefined && value !== null) form[key] = value }); const fields = this.loadArray(source, 'requiredFieldsJson', 'required_fields_json'); const attachments = this.loadArray(source, 'requiredAttachmentsJson', 'required_attachments_json'); const conditions = this.loadArray(source, 'conditionalRulesJson', 'conditional_rules_json'); const validators = this.loadArray(source, 'validatorRefsJson', 'validator_refs_json'); const messages = this.loadObject(source, 'errorMessagesJson', 'error_messages_json'); form.requiredFields = fields.value; form.requiredAttachments = attachments.value; form.conditionalRules = this.toConditions(conditions.value); form.validatorRefs = validators.value; form.errorMessages = this.toMessages(messages.value); form.dodRuleId = Number(form.dodRuleId) || null; form.version = Number(form.version) || 0; form.referenceCount = Number(form.referenceCount) || 0; form.serverStatus = form.status; this.raw = { requiredFieldsJson: fields.raw, requiredAttachmentsJson: attachments.raw, conditionalRulesJson: conditions.raw, validatorRefsJson: validators.raw, errorMessagesJson: messages.raw }; this.malformed = { requiredFieldsJson: fields.malformed, requiredAttachmentsJson: attachments.malformed, conditionalRulesJson: conditions.malformed, validatorRefsJson: validators.malformed, errorMessagesJson: messages.malformed }; if (this.copyMode) { form.dodRuleId = null; form.version = 0; form.referenceCount = 0; form.ruleCode = `${form.ruleCode || 'DOD'}_COPY`; } this.form = form; this.samplePayloadText = '{}'; this.sampleAttachments = []; this.testResult = null; this.initialSnapshot = this.snapshot(); this.$nextTick(() => this.$refs.form && this.$refs.form.clearValidate()) },
    loadArray(source, camel, snake) { const parsed = parseJson(valueOf(source, camel, snake), []); return Array.isArray(parsed.value) ? parsed : { ...parsed, value: [], malformed: true } },
    loadObject(source, camel, snake) { const parsed = parseJson(valueOf(source, camel, snake), {}); return parsed.value && !Array.isArray(parsed.value) && typeof parsed.value === 'object' ? parsed : { ...parsed, value: {}, malformed: true } },
    toConditions(entries) { return (entries || []).map(item => ({ field: item.field || '', when: { field: (item.when && item.when.field) || '', kind: item.when && Object.prototype.hasOwnProperty.call(item.when, 'equals') ? 'equals' : 'present', value: item.when && Object.prototype.hasOwnProperty.call(item.when, 'equals') ? item.when.equals : Boolean(item.when && item.when.present) } })) },
    toMessages(value) { return Object.entries(value || {}).map(([key, message]) => ({ key, message })) },
    repairArray(key, value) { if (!Array.isArray(value)) return this.$modal.msgError(`${key} 必须是 JSON 数组`); const property = key.replace('Json', ''); if (property === 'conditionalRules') this.form.conditionalRules = this.toConditions(value); else this.form[property] = value; this.raw[key] = JSON.stringify(value); this.malformed[key] = false },
    repairConditions(value) { if (!Array.isArray(value)) return this.$modal.msgError('conditionalRulesJson 必须是 JSON 数组'); this.form.conditionalRules = this.toConditions(value); this.raw.conditionalRulesJson = JSON.stringify(value); this.malformed.conditionalRulesJson = false },
    repairMessages(value) { if (!value || Array.isArray(value) || typeof value !== 'object') return this.$modal.msgError('errorMessagesJson 必须是 JSON 对象'); this.form.errorMessages = this.toMessages(value); this.raw.errorMessagesJson = JSON.stringify(value); this.malformed.errorMessagesJson = false },
    reset() { this.form = emptyForm(); this.initialSnapshot = ''; this.testResult = null; this.$emit('reset') },
    snapshot() { return JSON.stringify({ form: this.form, raw: this.raw, malformed: this.malformed }) },
    actionId(action) { return `dod-${action}-${Date.now()}-${Math.random().toString(16).slice(2)}` },
    validatorLabel(item) { return item.description ? `${item.code} · ${item.description}` : item.code },
    addCondition() { this.form.conditionalRules.push({ field: '', when: { field: '', kind: 'equals', value: '' } }) }, removeCondition(index) { this.form.conditionalRules.splice(index, 1) }, addMessage() { this.form.errorMessages.push({ key: '', message: '' }) }, removeMessage(index) { this.form.errorMessages.splice(index, 1) },
    conditionPayload() { return this.form.conditionalRules.map(item => ({ field: item.field, when: item.when.kind === 'equals' ? { field: item.when.field, equals: item.when.value } : { field: item.when.field, present: Boolean(item.when.value) } })) },
    messagePayload() { return this.form.errorMessages.reduce((result, item) => { if (item.key) result[item.key] = item.message; return result }, {}) },
    validateStructuredData() { const entries = this.conditionPayload(); const invalidCondition = entries.some(item => !item.field || !item.when.field || (Object.prototype.hasOwnProperty.call(item.when, 'equals') && (item.when.equals === undefined || item.when.equals === null || item.when.equals === ''))); if (invalidCondition) throw new Error('每条条件必填规则均需填写目标字段和条件字段/值'); const invalidMessages = this.form.errorMessages.some(item => !item.key || typeof item.message !== 'string'); if (invalidMessages) throw new Error('错误文案映射必须填写键和值') },
    payload() { this.validateStructuredData(); return { dodRuleId: this.persisted && !this.copyMode ? this.form.dodRuleId : null, ruleCode: this.form.ruleCode, ruleName: this.form.ruleName, ruleType: this.form.ruleType, requiredFieldsJson: JSON.stringify(this.form.requiredFields), requiredAttachmentsJson: JSON.stringify(this.form.requiredAttachments), conditionalRulesJson: JSON.stringify(this.conditionPayload()), validatorRefsJson: JSON.stringify(this.form.validatorRefs), errorMessagesJson: JSON.stringify(this.messagePayload()), status: this.persisted && !this.copyMode ? this.form.serverStatus : this.form.status, actionId: this.actionId('save'), expectedVersion: this.persisted && !this.copyMode ? Number(this.form.version) : 0 } },
    async validate() { if (this.hasMalformedStoredJson) throw new Error('请先修复所有异常的存储 JSON'); await this.$refs.form.validate(); this.validateStructuredData() },
    async save() { try { await this.validate(); this.saving = true; const payload = this.payload(); const response = await (payload.dodRuleId ? updateDodRule(payload.dodRuleId, payload) : createDodRule(payload)); this.$modal.msgSuccess('完成条件规则已保存'); this.finishSaved(response.data) } catch (error) { this.showError(error) } finally { this.saving = false } },
    async saveCopy() { try { await this.validate(); const id = valueOf(this.rule, 'dodRuleId', 'dod_rule_id'); if (!id) throw new Error('原规则不存在，无法复制'); this.copying = true; const response = await copyDodRule(id, { newRuleCode: this.form.ruleCode, actionId: this.actionId('copy') }); this.$modal.msgSuccess('完成条件规则副本已创建'); this.finishSaved(response.data) } catch (error) { this.showError(error) } finally { this.copying = false } },
    async toggle() { try { const targetStatus = this.form.serverStatus === '0' ? '1' : '0'; if (targetStatus === '1') { const response = await getDodRuleReferenceCount(this.form.dodRuleId); const count = Number(response.data || 0); await this.$confirm(`该规则当前被 ${count} 个模板引用。确认停用吗？`, '停用完成条件规则', { type: 'warning', confirmButtonText: '确认停用' }) } else await this.$confirm('确认启用此完成条件规则吗？', '启用完成条件规则', { type: 'warning' }); this.toggling = true; await toggleDodRule(this.form.dodRuleId, { status: targetStatus, actionId: this.actionId('toggle'), expectedVersion: Number(this.form.version) }); this.$modal.msgSuccess(targetStatus === '0' ? '规则已启用' : '规则已停用'); this.finishSaved() } catch (error) { if (error !== 'cancel') this.showError(error) } finally { this.toggling = false } },
    async runTest() { try { let payload; try { payload = JSON.parse(this.samplePayloadText || '{}') } catch (error) { throw new Error('样例 payload 必须是合法 JSON 对象') } if (!payload || Array.isArray(payload) || typeof payload !== 'object') throw new Error('样例 payload 必须是 JSON 对象'); this.testing = true; const response = await testDodRule(this.form.dodRuleId, { payload, attachments: this.sampleAttachments }); this.testResult = response.data || { passed: false, missingFields: [], missingAttachments: [], validatorIssues: [] } } catch (error) { this.showError(error) } finally { this.testing = false } },
    issueText(item) { return `${item.code || 'VALIDATION'}${item.path ? ` · ${item.path}` : ''}${item.message ? `：${item.message}` : ''}` }, finishSaved(savedId) { this.$emit('saved', savedId); this.$refs.drawer.closeAfterSave() }, format(value) { return value ? this.parseTime(value, '{y}-{m}-{d} {h}:{i}:{s}') : '-' }, showError(error) { if (error && error !== 'cancel') this.$modal.msgError((error && (error.msg || error.message)) || '操作失败，请稍后重试') }
  }
}
</script>

<style scoped lang="scss">
.full-width { width: 100%; }.drawer-note,.status-note { margin: 8px 0; color: #64748b; font-size: 12px; }.condition-row,.message-row { display: grid; grid-template-columns: minmax(100px,1fr) auto minmax(100px,1fr) 100px minmax(100px,1fr) auto; align-items: center; gap: 7px; margin-bottom: 8px; }.message-row { grid-template-columns: minmax(110px,.6fr) minmax(160px,1.4fr) auto; }.condition-kind { width: 100px; }.test-result { margin-top: 14px; padding: 12px; border: 1px solid #e5e7eb; border-radius: 6px; background: #fafcff; }.test-result strong { display: block; margin-top: 10px; }.test-result ul { margin: 5px 0; padding-left: 20px; }.malformed-editor .el-alert { margin-bottom: 8px; }.malformed-editor .el-button { margin-top: 8px; }@media (max-width: 740px) { .condition-row,.message-row { grid-template-columns: 1fr; } }
</style>
