<template>
  <config-page-shell title="完成条件规则管理" subtitle="以可复用 DoD 规则校验字段、材料、条件和服务端能力" :loading="loading" :empty="!loading && !rows.length" empty-text="暂无完成条件规则">
    <template #metrics><config-metric-card label="规则总数" :value="total" icon="el-icon-finished"/><config-metric-card label="已启用规则" :value="enabledCount" tone="success" icon="el-icon-circle-check"/><config-metric-card label="当前页被引用" :value="referencedCount" tone="warning" icon="el-icon-connection"/><config-metric-card label="当前页版本总和" :value="versionCount" tone="primary" icon="el-icon-document-copy"/></template>
    <template #filters><div class="rule-filters"><el-input v-model.trim="query.keyword" clearable placeholder="搜索规则编码或名称" @keyup.enter.native="search"/><el-select v-model="query.ruleType" clearable placeholder="规则类型" @change="search"><el-option v-for="item in dict.type.law_todo_dod_rule_type" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-select v-model="query.status" clearable placeholder="状态" @change="search"><el-option v-for="item in dict.type.law_todo_rule_status" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-button type="primary" icon="el-icon-search" @click="search">查询</el-button><el-button @click="resetQuery">重置</el-button><el-button v-hasPermi="['todo:dod-rule:create']" type="primary" icon="el-icon-plus" @click="openCreate">新增规则</el-button></div></template>
    <el-table v-loading="loading" :data="rows" stripe @row-click="openDetail"><el-table-column prop="ruleCode" label="规则编码" min-width="150"/><el-table-column prop="ruleName" label="规则名称" min-width="190"/><el-table-column label="规则类型" width="140"><template slot-scope="{ row }"><dict-tag :options="dict.type.law_todo_dod_rule_type" :value="field(row, 'ruleType', 'rule_type')" /></template></el-table-column><el-table-column label="引用模板" width="100" align="center"><template slot-scope="{ row }">{{ field(row, 'referenceCount', 'reference_count') || 0 }}</template></el-table-column><el-table-column label="状态" width="90"><template slot-scope="{ row }"><dict-tag :options="dict.type.law_todo_rule_status" :value="field(row, 'status', 'status')" /></template></el-table-column><el-table-column label="版本" width="80" align="center"><template slot-scope="{ row }">{{ field(row, 'version', 'version') || 0 }}</template></el-table-column><el-table-column label="更新时间" width="170"><template slot-scope="{ row }">{{ format(field(row, 'updateTime', 'update_time')) }}</template></el-table-column><el-table-column label="操作" fixed="right" width="210"><template slot-scope="{ row }"><el-button v-hasPermi="['todo:dod-rule:edit']" type="text" @click.stop="openEdit(row)">编辑</el-button><el-button v-hasPermi="['todo:dod-rule:copy']" type="text" @click.stop="openCopy(row)">复制</el-button><el-button v-hasPermi="['todo:dod-rule:toggle']" type="text" :loading="Boolean(rowToggleLoading[field(row, 'dodRuleId', 'dod_rule_id')])" @click.stop="toggleRow(row)">{{ field(row, 'status', 'status') === '0' ? '停用' : '启用' }}</el-button></template></el-table-column></el-table>
    <pagination v-show="total > 0" :total="total" :page.sync="query.pageNum" :limit.sync="query.pageSize" @pagination="load" />
    <dod-rule-drawer :visible.sync="drawerOpen" :rule="selected" :mode="drawerMode" @edit="openEdit" @copy="openCopy" @saved="afterSaved" />
  </config-page-shell>
</template>

<script>
import ConfigPageShell from '../shared/ConfigPageShell'
import ConfigMetricCard from '../shared/ConfigMetricCard'
import DodRuleDrawer from './DodRuleDrawer'
import { listDodRules, getDodRule, toggleDodRule, getDodRuleReferenceCount } from '@/api/todo-config'
export default {
  name: 'TodoDodRuleConfig', components: { ConfigPageShell, ConfigMetricCard, DodRuleDrawer }, dicts: ['law_todo_dod_rule_type', 'law_todo_rule_status'],
  data() { return { loading: false, total: 0, rows: [], query: { pageNum: 1, pageSize: 20, keyword: '', ruleType: '', status: '' }, drawerOpen: false, drawerMode: 'view', selected: null, rowToggleLoading: {} } },
  computed: { enabledCount() { return this.rows.filter(row => this.field(row, 'status', 'status') === '0').length }, referencedCount() { return this.rows.filter(row => Number(this.field(row, 'referenceCount', 'reference_count') || 0) > 0).length }, versionCount() { return this.rows.reduce((total, row) => total + Number(this.field(row, 'version', 'version') || 0), 0) } },
  created() { this.load() },
  methods: { field(row, camel, snake) { return row && (row[camel] !== undefined ? row[camel] : row[snake]) }, format(value) { return value ? this.parseTime(value, '{y}-{m}-{d} {h}:{i}:{s}') : '-' }, actionId(action) { return `dod-${action}-${Date.now()}-${Math.random().toString(16).slice(2)}` }, async load() { this.loading = true; try { const response = await listDodRules(this.query); this.rows = response.rows || []; this.total = Number(response.total || 0) } catch (error) { this.rows = []; this.total = 0; this.$modal.msgError((error && (error.msg || error.message)) || '加载完成条件规则失败') } finally { this.loading = false } }, search() { this.query.pageNum = 1; this.load() }, resetQuery() { this.query = { pageNum: 1, pageSize: 20, keyword: '', ruleType: '', status: '' }; this.load() }, openCreate() { this.selected = null; this.drawerMode = 'create'; this.drawerOpen = true }, async openDetail(row) { await this.openWithMode(row, 'view') }, async openEdit(row) { await this.openWithMode(row, 'edit') }, async openCopy(row) { await this.openWithMode(row, 'copy') }, async openWithMode(row, mode) { try { const id = this.field(row, 'dodRuleId', 'dod_rule_id'); const response = await getDodRule(id); this.selected = response.data || row; this.drawerMode = mode; this.drawerOpen = true } catch (error) { this.$modal.msgError((error && (error.msg || error.message)) || '加载规则详情失败') } }, async toggleRow(row) { const id = this.field(row, 'dodRuleId', 'dod_rule_id'); if (!id || this.rowToggleLoading[id]) return; const targetStatus = this.field(row, 'status', 'status') === '0' ? '1' : '0'; this.$set(this.rowToggleLoading, id, true); try { if (targetStatus === '1') { const response = await getDodRuleReferenceCount(id); const count = Number(response.data || 0); await this.$confirm(`该规则当前被 ${count} 个模板引用。确认停用吗？`, '停用完成条件规则', { type: 'warning', confirmButtonText: '确认停用' }) } else await this.$confirm('确认启用此完成条件规则吗？', '启用完成条件规则', { type: 'warning' }); await toggleDodRule(id, { status: targetStatus, actionId: this.actionId('row-toggle'), expectedVersion: Number(this.field(row, 'version', 'version') || 0) }); this.$modal.msgSuccess(targetStatus === '0' ? '规则已启用' : '规则已停用'); this.load() } catch (error) { if (error !== 'cancel') this.$modal.msgError((error && (error.msg || error.message)) || '状态更新失败') } finally { this.$set(this.rowToggleLoading, id, false) } }, afterSaved() { this.drawerOpen = false; this.load() } }
}
</script>

<style scoped lang="scss">.rule-filters { display: flex; flex-wrap: wrap; gap: 8px; }.rule-filters .el-input { width: 230px; }.rule-filters .el-select { width: 140px; }</style>
