<template>
  <config-page-shell title="SLA 规则管理" subtitle="集中维护时限、工作日历和固定 80/100/150 升级语义" :loading="loading" :empty="!loading && !rows.length" empty-text="暂无 SLA 规则">
    <template #metrics><config-metric-card label="规则总数" :value="total" icon="el-icon-time"/><config-metric-card label="已启用规则" :value="dashboard.enabledSlaRuleCount || 0" tone="success" icon="el-icon-circle-check"/><config-metric-card label="当前页响应型" :value="responseCount" tone="warning" icon="el-icon-alarm-clock"/><config-metric-card label="当前页执行型" :value="executionCount" tone="primary" icon="el-icon-timer"/></template>
    <template #filters><div class="rule-filters"><el-input v-model.trim="query.keyword" clearable placeholder="搜索规则编码或名称" @keyup.enter.native="search"/><el-select v-model="query.slaType" clearable placeholder="SLA 类型" @change="search"><el-option v-for="item in dict.type.law_todo_sla_type" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-select v-model="query.status" clearable placeholder="状态" @change="search"><el-option v-for="item in dict.type.law_todo_rule_status" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-button type="primary" icon="el-icon-search" @click="search">查询</el-button><el-button @click="resetQuery">重置</el-button><el-button v-hasPermi="['todo:sla-rule:create']" type="primary" icon="el-icon-plus" @click="openCreate">新增规则</el-button></div></template>
    <el-table v-loading="loading" :data="rows" stripe @row-click="openDetail"><el-table-column prop="ruleCode" label="规则编码" min-width="150"/><el-table-column prop="ruleName" label="规则名称" min-width="180"/><el-table-column label="SLA 类型" width="130"><template slot-scope="{ row }"><dict-tag :options="dict.type.law_todo_sla_type" :value="field(row, 'slaType', 'sla_type')" /></template></el-table-column><el-table-column label="时限" width="120"><template slot-scope="{ row }">{{ field(row, 'durationValue', 'duration_value') }} {{ label(dict.type.law_todo_sla_unit, field(row, 'durationUnit', 'duration_unit')) }}</template></el-table-column><el-table-column label="工作日历" min-width="140"><template slot-scope="{ row }">{{ field(row, 'calendarCode', 'calendar_code') }}</template></el-table-column><el-table-column label="计时起点" min-width="130"><template slot-scope="{ row }"><dict-tag :options="dict.type.law_todo_sla_start_strategy" :value="field(row, 'startStrategy', 'start_strategy')" /></template></el-table-column><el-table-column label="引用模板" width="96" align="center"><template slot-scope="{ row }">{{ field(row, 'referenceCount', 'reference_count') || 0 }}</template></el-table-column><el-table-column label="状态" width="90"><template slot-scope="{ row }"><dict-tag :options="dict.type.law_todo_rule_status" :value="field(row, 'status', 'status')" /></template></el-table-column><el-table-column label="更新时间" width="170"><template slot-scope="{ row }">{{ format(field(row, 'updateTime', 'update_time')) }}</template></el-table-column><el-table-column label="操作" fixed="right" width="210"><template slot-scope="{ row }"><el-button v-hasPermi="['todo:sla-rule:edit']" type="text" @click.stop="openEdit(row)">编辑</el-button><el-button v-hasPermi="['todo:sla-rule:copy']" type="text" @click.stop="openCopy(row)">复制</el-button><el-button v-hasPermi="['todo:sla-rule:toggle']" type="text" @click.stop="openDetail(row)">{{ field(row, 'status', 'status') === '0' ? '停用' : '启用' }}</el-button></template></el-table-column></el-table>
    <pagination v-show="total > 0" :total="total" :page.sync="query.pageNum" :limit.sync="query.pageSize" @pagination="load" />
    <sla-rule-drawer :visible.sync="drawerOpen" :rule="selected" :mode="drawerMode" @edit="openEdit" @copy="openCopy" @saved="afterSaved" />
  </config-page-shell>
</template>

<script>
import ConfigPageShell from '../shared/ConfigPageShell'
import ConfigMetricCard from '../shared/ConfigMetricCard'
import SlaRuleDrawer from './SlaRuleDrawer'
import { getTodoConfigDashboard, listSlaRules, getSlaRule } from '@/api/todo-config'
export default {
  name: 'TodoSlaRuleConfig', components: { ConfigPageShell, ConfigMetricCard, SlaRuleDrawer },
  dicts: ['law_todo_sla_type', 'law_todo_sla_unit', 'law_todo_sla_start_strategy', 'law_todo_timeout_strategy', 'law_todo_rule_status'],
  data() { return { loading: false, total: 0, rows: [], dashboard: {}, query: { pageNum: 1, pageSize: 20, keyword: '', slaType: '', status: '' }, drawerOpen: false, drawerMode: 'view', selected: null } },
  computed: { responseCount() { return this.rows.filter(row => this.field(row, 'slaType', 'sla_type') === 'RESPONSE').length }, executionCount() { return this.rows.filter(row => this.field(row, 'slaType', 'sla_type') === 'EXECUTION').length } },
  created() { this.loadDashboard(); this.load() },
  methods: { field(row, camel, snake) { return row && (row[camel] !== undefined ? row[camel] : row[snake]) }, label(options, value) { const item = (options || []).find(option => option.value === value); return item ? item.label : (value || '-') }, format(value) { return value ? this.parseTime(value, '{y}-{m}-{d} {h}:{i}:{s}') : '-' }, async loadDashboard() { try { const response = await getTodoConfigDashboard(); this.dashboard = response.data || {} } catch (error) { this.dashboard = {} } }, async load() { this.loading = true; try { const response = await listSlaRules(this.query); this.rows = response.rows || []; this.total = Number(response.total || 0) } catch (error) { this.rows = []; this.total = 0; this.$modal.msgError((error && (error.msg || error.message)) || '加载 SLA 规则失败') } finally { this.loading = false } }, search() { this.query.pageNum = 1; this.load() }, resetQuery() { this.query = { pageNum: 1, pageSize: 20, keyword: '', slaType: '', status: '' }; this.load() }, openCreate() { this.selected = null; this.drawerMode = 'create'; this.drawerOpen = true }, async openDetail(row) { try { const id = this.field(row, 'slaRuleId', 'sla_rule_id'); const response = await getSlaRule(id); this.selected = response.data || row; this.drawerMode = 'view'; this.drawerOpen = true } catch (error) { this.$modal.msgError((error && (error.msg || error.message)) || '加载规则详情失败') } }, async openEdit(row) { try { const id = this.field(row, 'slaRuleId', 'sla_rule_id'); const response = await getSlaRule(id); this.selected = response.data || row; this.drawerMode = 'edit'; this.drawerOpen = true } catch (error) { this.$modal.msgError((error && (error.msg || error.message)) || '加载规则详情失败') } }, async openCopy(row) { try { const id = this.field(row, 'slaRuleId', 'sla_rule_id'); const response = await getSlaRule(id); this.selected = response.data || row; this.drawerMode = 'copy'; this.drawerOpen = true } catch (error) { this.$modal.msgError((error && (error.msg || error.message)) || '加载规则详情失败') } }, afterSaved() { this.drawerOpen = false; this.loadDashboard(); this.load() } }
}
</script>

<style scoped lang="scss">.rule-filters { display: flex; flex-wrap: wrap; gap: 8px; }.rule-filters .el-input { width: 230px; }.rule-filters .el-select { width: 140px; }</style>
